{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of employees per sector",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Technology",
     "target": "SELECT timestamp_column, SUM(number_of_employees) FROM spark_streams.companies_created WHERE sector='Technology' ALLOW FILTERING;"
    },
    {
     "alias": "Retail",
     "target": "SELECT timestamp_column, SUM(number_of_employees) FROM spark_streams.companies_created WHERE sector='Retail' ALLOW FILTERING;"
    },
    {
     "alias": "Healthcare",
     "target": "SELECT timestamp_column, SUM(number_of_employees) FROM spark_streams.companies_created WHERE sector='Healthcare' ALLOW FILTERING;"
    },
    {
     "alias": "Finance",
     "target": "SELECT timestamp_column, SUM(number_of_employees) FROM spark_streams.companies_created WHERE sector='Finance' ALLOW FILTERING;"
    },
    {
     "alias": "Agriculture",
     "target": "SELECT timestamp_column, SUM(number_of_employees) FROM spark_streams.companies_created WHERE sector='Agriculture' ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Number of companies per sector ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Technology",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE sector='Technology' ALLOW FILTERING;"
    },
    {
     "alias": "Healthcare",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE sector='Healthcare' ALLOW FILTERING;"
    },
    {
     "alias": "Finance",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE sector='Finance' ALLOW FILTERING;"
    },
    {
     "alias": "Finance",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE sector='Retail' ALLOW FILTERING;"
    },
    {
     "alias": "Finance",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE sector='Agriculture' ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Analyzing company size",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "small companies",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE number_of_employees >= 10 AND number_of_employees < 49 ALLOW FILTERING;\n"
    },
    {
     "alias": "medium-sized companies",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE number_of_employees >= 50 AND number_of_employees < 249 ALLOW FILTERING;\n"
    },
    {
     "alias": "large companies",
     "target": "SELECT timestamp_column, COUNT(name) FROM spark_streams.companies_created WHERE number_of_employees >= 250  ALLOW FILTERING;\n"
    }
   ]
  },
  {
   "title": "revenue as a percentage of investment by country ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "France",
     "target": "SELECT timestamp_column, country, SUM(revenue) / SUM(investment_received) * 100 AS investment_percentage FROM spark_streams.companies_created WHERE country='France' ALLOW FILTERING;"
    },
    {
     "alias": "Singapore",
     "target": "SELECT timestamp_column, country, SUM(revenue) / SUM(investment_received) * 100 AS investment_percentage FROM spark_streams.companies_created WHERE country='Singapore' ALLOW FILTERING;"
    },
    {
     "alias": "Australia",
     "target": "SELECT timestamp_column, country,  SUM(revenue) / SUM(investment_received) * 100 AS investment_percentage FROM spark_streams.companies_created WHERE country='Australia' ALLOW FILTERING;"
    },
    {
     "alias": "Morocco",
     "target": "SELECT timestamp_column, country,  SUM(revenue) / SUM(investment_received) * 100 AS investment_percentage FROM spark_streams.companies_created WHERE country='Morocco' ALLOW FILTERING;"
    },
    {
     "alias": "Mexico",
     "target": "SELECT timestamp_column, country,  SUM(revenue) / SUM(investment_received) * 100 AS investment_percentage FROM spark_streams.companies_created WHERE country='Mexico' ALLOW FILTERING;"
    },
    {
     "alias": "Egypt",
     "target": "SELECT timestamp_column, country,  SUM(revenue) / SUM(investment_received) * 100 AS investment_percentage FROM spark_streams.companies_created WHERE country='Egypt' ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Average number of employees per country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "France ",
     "target": "select timestamp_column, country, AVG(number_of_employees) AS average_revenue from spark_streams.companies_created WHERE country='France' ALLOW FILTERING;"
    },
    {
     "alias": "Egypt",
     "target": "select timestamp_column, country, AVG(number_of_employees) AS average_revenue from spark_streams.companies_created WHERE country='Egypt' ALLOW FILTERING;"
    },
    {
     "alias": "Morocco",
     "target": "select timestamp_column, country, AVG(number_of_employees) AS average_revenue from spark_streams.companies_created WHERE country='Morocco' ALLOW FILTERING;"
    },
    {
     "alias": "Australia",
     "target": "select timestamp_column, country, AVG(number_of_employees) AS average_revenue from spark_streams.companies_created WHERE country='Australia' ALLOW FILTERING;"
    },
    {
     "alias": "Mexico",
     "target": "select timestamp_column, country, AVG(number_of_employees) AS average_revenue from spark_streams.companies_created WHERE country='Mexico' ALLOW FILTERING;"
    },
    {
     "alias": "Singapore",
     "target": "select timestamp_column, country, AVG(number_of_employees) AS average_revenue from spark_streams.companies_created WHERE country='Singapore' ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Revenue average per country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "France",
     "target": "select timestamp_column, country, AVG(revenue) AS average_revenue from spark_streams.companies_created WHERE country='France' ALLOW FILTERING;"
    },
    {
     "alias": "Morocco",
     "target": "select timestamp_column, country, AVG(revenue) AS average_revenue from spark_streams.companies_created WHERE country='Morocco' ALLOW FILTERING;"
    },
    {
     "alias": "Australia",
     "target": "select timestamp_column, country, AVG(revenue) AS average_revenue from spark_streams.companies_created WHERE country='Australia' ALLOW FILTERING;"
    },
    {
     "alias": "Egypt",
     "target": "select timestamp_column, country, AVG(revenue) AS average_revenue from spark_streams.companies_created WHERE country='Egypt' ALLOW FILTERING;"
    },
    {
     "alias": "Mexico",
     "target": "select timestamp_column, country, AVG(revenue) AS average_revenue from spark_streams.companies_created WHERE country='Mexico' ALLOW FILTERING;"
    },
    {
     "alias": "Singapore",
     "target": "select timestamp_column, country, AVG(revenue) AS average_revenue from spark_streams.companies_created WHERE country='Singapore' ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "Average investment per country",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "alias": "france",
     "target": "select timestamp_column, country, AVG(investment_received) AS average_investment from spark_streams.companies_created WHERE country='France' ALLOW FILTERING;"
    },
    {
     "alias": "Egypt",
     "target": "select timestamp_column, country, AVG(investment_received) AS average_investment from spark_streams.companies_created WHERE country='Egypt' ALLOW FILTERING;"
    },
    {
     "alias": "Australia",
     "target": "select timestamp_column, country, AVG(investment_received) AS average_investment from spark_streams.companies_created WHERE country='Australia' ALLOW FILTERING;"
    },
    {
     "alias": "Morocco",
     "target": "select timestamp_column, country, AVG(investment_received) AS average_investment from spark_streams.companies_created WHERE country='Morocco' ALLOW FILTERING;"
    },
    {
     "alias": "Singapore",
     "target": "select timestamp_column, country, AVG(investment_received) AS average_investment from spark_streams.companies_created WHERE country='Mexico' ALLOW FILTERING;"
    },
    {
     "alias": "Luxembourg",
     "target": "select timestamp_column, country, AVG(investment_received) AS average_investment from spark_streams.companies_created WHERE country='Luxembourg' ALLOW FILTERING;"
    }
   ]
  },
  {
   "title": "investement received for all companies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "keyspace": "spark_streams",
     "target": "select timestamp_column, investment_received from spark_streams.companies_created;"
    }
   ]
  }
 ]
}